### PR TITLE
Plotting correlation maps from seed

### PR DESCRIPTION
**Pull request by juchitel1**
Hi Rob,
It seemed like some lab members liked the idea of having this, so I thought that maybe I should just submit a pull request to add it to the toolbox rather than just post it in the code slack channel. If you think it's too raw and needs more development being toolbox approved, no worries whatsoever, I'll just post it in the channel if any one wants it that way.
Julie

### CODE REVIEW

**Comment by juchitel1** [comment]
Hi Rob,
It seemed like some lab members liked the idea of having this, so I thought that maybe I should just submit a pull request to add it to the toolbox rather than just post it in the code slack channel. If you think it's too raw and needs more development being toolbox approved, no worries whatsoever, I'll just post it in the channel if any one wants it that way.
Julie

**Comment by RJCooperUCL** [comment]
Hi Julie - do you still want to add this function to the toolbox? (I am only 8 months late)!

If you do please follow the funciton naming convention and the comments structure inside the .m. This funciton should be in the Library folder and be called DOTHUB_seedSelectCorrMap.m

**Comment by juchitel1** [comment]
Hi Rob, I made some changes (including the title) and to make the correlation coefficients themselves an output

**Comment by juchitel1** [comment]
Hi, I just submitted some edits!
Julie

**Pull request closed without merging**
